apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "xgboost-iris"
spec:
  predictor:
    sklearn:
      protocolVersion: "v2"
      storageUri: "pvc://xgboostlocal/iris_model.joblib"
      