# PIPELINE DEFINITION
# Name: xgboost-train-pipeline
# Inputs:
#    claim: str
#    masters: float
#    max_time: float
#    model_name: str
#    serve_manifest_url: str
#    storage: float
#    timeout: float
#    train_manifest_url: str
#    workers: float
components:
  comp-create-inference-service:
    executorLabel: exec-create-inference-service
    inputDefinitions:
      parameters:
        max_timeout:
          parameterType: NUMBER_DOUBLE
        name:
          parameterType: STRING
        raw_manifest_url:
          parameterType: STRING
        storageUri:
          parameterType: STRING
        timeout_period:
          parameterType: NUMBER_DOUBLE
  comp-create-volume:
    executorLabel: exec-create-volume
    inputDefinitions:
      parameters:
        max_timeout:
          parameterType: NUMBER_DOUBLE
        pvc_name:
          parameterType: STRING
        storage_size:
          parameterType: NUMBER_DOUBLE
        timeout_period:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      parameters:
        Output:
          parameterType: STRING
  comp-xgboost-train:
    executorLabel: exec-xgboost-train
    inputDefinitions:
      parameters:
        claim_name:
          parameterType: STRING
        master_replicas:
          parameterType: NUMBER_DOUBLE
        max_timeout:
          parameterType: NUMBER_DOUBLE
        raw_manifest_url:
          parameterType: STRING
        timeout_period:
          parameterType: NUMBER_DOUBLE
        worker_replicas:
          parameterType: NUMBER_DOUBLE
deploymentSpec:
  executors:
    exec-create-inference-service:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - create_inference_service
        command:
        - python3
        - -m
        - kfp.dsl.executor_main
        image: chasechristensen/xgboost_serve_component:v3
    exec-create-volume:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - create_volume
        command:
        - python3
        - -m
        - kfp.dsl.executor_main
        image: chasechristensen/volume_component:v2
    exec-xgboost-train:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - xgboost_train
        command:
        - python3
        - -m
        - kfp.dsl.executor_main
        image: chasechristensen/xgboost_train_component:v2
pipelineInfo:
  name: xgboost-train-pipeline
root:
  dag:
    tasks:
      create-inference-service:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-create-inference-service
        dependentTasks:
        - create-volume
        - xgboost-train
        inputs:
          parameters:
            max_timeout:
              componentInputParameter: max_time
            name:
              componentInputParameter: model_name
            raw_manifest_url:
              componentInputParameter: serve_manifest_url
            storageUri:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: create-volume
            timeout_period:
              componentInputParameter: timeout
        taskInfo:
          name: create-inference-service
      create-volume:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-create-volume
        inputs:
          parameters:
            max_timeout:
              componentInputParameter: max_time
            pvc_name:
              componentInputParameter: claim
            storage_size:
              componentInputParameter: storage
            timeout_period:
              componentInputParameter: timeout
        taskInfo:
          name: create-volume
      xgboost-train:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-xgboost-train
        dependentTasks:
        - create-volume
        inputs:
          parameters:
            claim_name:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: create-volume
            master_replicas:
              componentInputParameter: masters
            max_timeout:
              componentInputParameter: max_time
            raw_manifest_url:
              componentInputParameter: train_manifest_url
            timeout_period:
              componentInputParameter: timeout
            worker_replicas:
              componentInputParameter: workers
        taskInfo:
          name: xgboost-train
  inputDefinitions:
    parameters:
      claim:
        parameterType: STRING
      masters:
        parameterType: NUMBER_DOUBLE
      max_time:
        parameterType: NUMBER_DOUBLE
      model_name:
        parameterType: STRING
      serve_manifest_url:
        parameterType: STRING
      storage:
        parameterType: NUMBER_DOUBLE
      timeout:
        parameterType: NUMBER_DOUBLE
      train_manifest_url:
        parameterType: STRING
      workers:
        parameterType: NUMBER_DOUBLE
schemaVersion: 2.1.0
sdkVersion: kfp-2.4.0
